import  apple  from './images/logos/apple.png'
import  Creative  from './images/logos/Creative.png'
import  dropbox  from './images/logos/dropbox.png'
import  envato from './images/logos/envato.png'
import google from './images/logos/google.png'
import spotify from './images/logos/spotify.png'
import paypal from './images/logos/paypal.png'
import meta  from './images/logos/meta.png'
import yelp  from './images/logos/yelp.png'
import twitter from './images/logos/twitter.png'
import microsoft  from './images/logos/microsoft.png'
import image16 from './images/avatar/image16.jpg'
import image17 from './images/avatar/image17.jpg'
import image18 from './images/avatar/image18.jpg'
import image19 from './images/avatar/image19.jpg'
import image20 from './images/avatar/image20.jpg'
import image6 from './images/jobs/image6.jpg'
import image7 from './images/jobs/image8.jpg'
import image8 from './images/jobs/image9.jpg'
import image9 from './images/jobs/image9.jpg'
import image10 from './images/jobs/image10.jpg'
import image11 from './images/jobs/image11.jpg'
import image12 from './images/jobs/image12.jpg'
import image13 from './images/jobs/image13.jpg'
import image14 from './images/jobs/image14.jpg'
import { FaFacebook } from 'react-icons/fa6'
export const info = [
    {
        id: 0,
        image: google,
        title: "Technical Lead",
        country: " Kuala, Malaysia",
        hours: "10 hours ago",
        salary: "$20k",
        level: "Internship",
        workTime: "Freelance",
    },
    {
        id: 1,
        image: apple,
        title: "Business Director",
        country: " California, USA",
        hours: "1 day ago",
        salary: "$90k",
        level: "Senior",
        workTime: "Full Time",
    },
    {
        id: 2,
        image: meta,
        title: "HR Manager",
        country: " Tower, Paris",
        hours: "22 hours ago",
        salary: "$50k",
        level: "Senior",
        workTime: "Part Time",
    },
    {
        id: 3,
        image: dropbox,
        title: "Dev Ops",
        country: "Thailand",
        hours: "40 minutes ago",
        salary: " $75k-80k",
        level: "Senior",
        workTime: "Part Time",
    },
    {
        id: 4,
        image: Creative,
        title: "UX Designer",
        country: " Kuala, Malaysia",
        hours: " 2 hours ago",
        salary: "$100k",
        level: "Entry",
        workTime: "Remote",
    },
]
export const informationJobs = [
    {
        id: 0,
        image1: image6,
        image2: microsoft,
        title: "Technical Lead",
        company: "Salesforce",
        level: "Internship",
        typeWork: "Freelance",
        location: " Kuala, Malaysia",
        workTime: " 10 hours ago",
        salary: " $50k",
    },
    {
        id: 1,
        title: "Marketing Assistant",
        company: "Spotify",
        level: "Senior", 
        image1: image7,
        image2: spotify,
        typeWork: "Part Time",
        location: " California, USA",
        workTime: "8 days ago",
        salary: " $20k",
    },
    {
        id: 2,
        image1: image8,
        image2: twitter,
        title: "Programmer",
        company: "Twiter",
        level: "Senior",
        typeWork: "Part Time",
        location: " California, USA",
        workTime: "8 days ago",
        salary: " $20k",
    },
    {
        id: 3,
        image1: image10,
        image2: yelp,
        title: "HR Manager",
        company: "Yelp",
        level: "Senior",
        typeWork: "Part Time",
        location: " California, USA",
        workTime: "15 hours ago",
        salary: "$35k - 45k",
    },
    {
        id: 4,
        image1: image11,
        image2: paypal,
        title: "Sales Representative",
        company: "Paypal",
        level: "Junior",
        typeWork: "Contract",
        location: " Bangkok, Thailand",
        workTime: "20 days ago",
        salary: "$20k - 35k",
    },
    {
        id: 5,
        image1: image13,
        image2: envato,
        title: "Graphic Designer",
        company: "Envato",
        level: "Mid Level",
        typeWork: "Full Time",
        location: "Melbourne, Australia",
        workTime: "2 days ago",
        salary: " $20k",
    },]
    export const NewJobs = [
        {
            id: 0,
            image1: image6,
            image2: microsoft,
            title: "Technical Lead",
            company: "Salesforce",
            level: "Internship",
            typeWork: "Freelance",
            location: " Kuala, Malaysia",
            workTime: " 10 hours ago",
            salary: " $50k",
        },
        {
            id: 1,
            title: "Marketing Assistant",
            company: "Spotify",
            level: "Senior", 
            image1: image7,
            image2: spotify,
            typeWork: "Part Time",
            location: " California, USA",
            workTime: "8 days ago",
            salary: " $20k",
        },
        {
            id: 2,
            image1: image8,
            image2: twitter,
            title: "Programmer",
            company: "Twiter",
            level: "Senior",
            typeWork: "Part Time",
            location: " California, USA",
            workTime: "8 days ago",
            salary: " $20k",
        },
        {
            id: 3,
            image1: image10,
            image2: yelp,
            title: "HR Manager",
            company: "Yelp",
            level: "Senior",
            typeWork: "Part Time",
            location: " California, USA",
            workTime: "15 hours ago",
            salary: "$35k - 45k",
        },
        {
            id: 4,
            image1: image11,
            image2: paypal,
            title: "Sales Representative",
            company: "Paypal",
            level: "Junior",
            typeWork: "Contract",
            location: " Bangkok, Thailand",
            workTime: "20 days ago",
            salary: "$20k - 35k",
        },
        {
            id: 5,
            image1: image13,
            image2: envato,
            title: "Graphic Designer",
            company: "Envato",
            level: "Mid Level",
            typeWork: "Full Time",
            location: "Melbourne, Australia",
            workTime: "2 days ago",
            salary: " $20k",
        },
        {
            id: 6,
            image1: image11,
            image2: paypal,
            title: "Sales Representative",
            company: "Paypal",
            level: "Senior",
            typeWork: "Contract",
            location: "Melbourne, Australia",
            workTime: "20 days ago",
            salary: "$100k - 50k",
        },
        {
            id: 7,
            image1: image14,
            image2: twitter,
            title: "Programmer",
            company: "Twiter",
            level: "Senior",
            typeWork: "Full Time",
            location: " California, USA",
            workTime: "8 days ago",
            salary: " $30k",
        },
        {
            id: 8,
            title: "Marketing Assistant",
            company: "Spotify",
            level: "Senior", 
            image1: image10,
            image2: spotify,
            typeWork: "Full Time",
            location: " California, USA",
            workTime: "8 days ago",
            salary: " $2k",
        },
        {
            id: 9,
            title: "Front End Devloper",
            company: "Facebook",
            level: "Junior", 
            image1: image10,
            image2: dropbox,
            typeWork: "Full Time",
            location: " California, USA",
            workTime: "8 days ago",
            salary: " $20k",
        },
        {
            id: 10,
            image1: image16,
            image2: microsoft,
            title: "Technical Lead",
            company: "Salesforce",
            level: "Internship",
            typeWork: "Freelance",
            location: " Kuala, Malaysia",
            workTime: " 10 hours ago",
            salary: " $5k - $10k",
        },
        
    ]
    export const lastJobs = [
        {
            id: 0,
            image1: image6,
            image2: microsoft,
            title: "Technical Lead",
            company: "Salesforce",
            level: "Internship",
            typeWork: "Freelance",
            location: " Kuala, Malaysia",
            workTime: " 10 hours ago",
            salary: " $50k",
        },
        {
            id: 1,
            title: "Marketing Assistant",
            company: "Spotify",
            level: "Senior", 
            image1: image7,
            image2: spotify,
            typeWork: "Part Time",
            location: " California, USA",
            workTime: "8 days ago",
            salary: " $20k",
        },
        {
            id: 2,
            image1: image8,
            image2: twitter,
            title: "Programmer",
            company: "Twiter",
            level: "Senior",
            typeWork: "Part Time",
            location: " California, USA",
            workTime: "8 days ago",
            salary: " $20k",
        },
        {
            id: 3,
            image1: image10,
            image2: yelp,
            title: "HR Manager",
            company: "Yelp",
            level: "Senior",
            typeWork: "Part Time",
            location: " California, USA",
            workTime: "15 hours ago",
            salary: "$35k - 45k",
        },
        {
            id: 4,
            image1: image11,
            image2: paypal,
            title: "Sales Representative",
            company: "Paypal",
            level: "Junior",
            typeWork: "Contract",
            location: " Bangkok, Thailand",
            workTime: "20 days ago",
            salary: "$20k - 35k",
        },
        {
            id: 5,
            image1: image13,
            image2: envato,
            title: "Graphic Designer",
            company: "Envato",
            level: "Mid Level",
            typeWork: "Full Time",
            location: "Melbourne, Australia",
            workTime: "2 days ago",
            salary: " $20k",
        },
        {
            id: 6,
            image1: image11,
            image2: paypal,
            title: "Sales Representative",
            company: "Paypal",
            level: "Senior",
            typeWork: "Contract",
            location: "Melbourne, Australia",
            workTime: "20 days ago",
            salary: "$100k - 50k",
        },
        {
            id: 7,
            image1: image14,
            image2: twitter,
            title: "Programmer",
            company: "Twiter",
            level: "Senior",
            typeWork: "Full Time",
            location: " California, USA",
            workTime: "8 days ago",
            salary: " $30k",
        },
        {
            id: 8,
            title: "Marketing Assistant",
            company: "Spotify",
            level: "Senior", 
            image1: image10,
            image2: spotify,
            typeWork: "Full Time",
            location: " California, USA",
            workTime: "8 days ago",
            salary: " $2k",
        },
        {
            id: 9,
            title: "Front End Devloper",
            company: "Facebook",
            level: "Junior", 
            image1: image10,
            image2: dropbox,
            typeWork: "Full Time",
            location: " California, USA",
            workTime: "8 days ago",
            salary: " $20k",
        },
        {
            id: 10,
            image1: image16,
            image2: microsoft,
            title: "Technical Lead",
            company: "Salesforce",
            level: "Internship",
            typeWork: "Freelance",
            location: " Kuala, Malaysia",
            workTime: " 10 hours ago",
            salary: " $5k - $10k",
        },
        
    ]
    export const Highedsalaryjobs = [
        {
            id: 0,
            image1: image6,
            image2: microsoft,
            title: "Technical Lead",
            company: "Salesforce",
            level: "Internship",
            typeWork: "Freelance",
            location: " Kuala, Malaysia",
            workTime: " 10 hours ago",
            salary: " $50k",
        },
        {
            id: 1,
            title: "Marketing Assistant",
            company: "Spotify",
            level: "Senior", 
            image1: image7,
            image2: spotify,
            typeWork: "Part Time",
            location: " California, USA",
            workTime: "8 days ago",
            salary: " $20k",
        },
        {
            id: 2,
            image1: image8,
            image2: twitter,
            title: "Programmer",
            company: "Twiter",
            level: "Senior",
            typeWork: "Part Time",
            location: " California, USA",
            workTime: "8 days ago",
            salary: " $20k",
        },
        {
            id: 3,
            image1: image10,
            image2: yelp,
            title: "HR Manager",
            company: "Yelp",
            level: "Senior",
            typeWork: "Part Time",
            location: " California, USA",
            workTime: "15 hours ago",
            salary: "$35k - 45k",
        },
        {
            id: 4,
            image1: image11,
            image2: paypal,
            title: "Sales Representative",
            company: "Paypal",
            level: "Junior",
            typeWork: "Contract",
            location: " Bangkok, Thailand",
            workTime: "20 days ago",
            salary: "$20k - 35k",
        },
        {
            id: 5,
            image1: image13,
            image2: envato,
            title: "Graphic Designer",
            company: "Envato",
            level: "Mid Level",
            typeWork: "Full Time",
            location: "Melbourne, Australia",
            workTime: "2 days ago",
            salary: " $20k",
        },
        {
            id: 6,
            image1: image11,
            image2: paypal,
            title: "Sales Representative",
            company: "Paypal",
            level: "Senior",
            typeWork: "Contract",
            location: "Melbourne, Australia",
            workTime: "20 days ago",
            salary: "$100k - 50k",
        },
        {
            id: 7,
            image1: image14,
            image2: twitter,
            title: "Programmer",
            company: "Twiter",
            level: "Senior",
            typeWork: "Full Time",
            location: " California, USA",
            workTime: "8 days ago",
            salary: " $30k",
        },
        {
            id: 8,
            title: "Marketing Assistant",
            company: "Spotify",
            level: "Senior", 
            image1: image10,
            image2: spotify,
            typeWork: "Full Time",
            location: " California, USA",
            workTime: "8 days ago",
            salary: " $2k",
        },
        {
            id: 9,
            title: "Front End Devloper",
            company: "Facebook",
            level: "Junior", 
            image1: image10,
            image2: dropbox,
            typeWork: "Full Time",
            location: " California, USA",
            workTime: "8 days ago",
            salary: " $20k",
        },
        {
            id: 10,
            image1: image16,
            image2: microsoft,
            title: "Technical Lead",
            company: "Salesforce",
            level: "Internship",
            typeWork: "Freelance",
            location: " Kuala, Malaysia",
            workTime: " 10 hours ago",
            salary: " $5k - $10k",
        },
        
    ]
    export const Internshipjobs = [
        {
            id: 0,
            image1: image6,
            image2: microsoft,
            title: "Technical Lead",
            company: "Salesforce",
            level: "Internship",
            typeWork: "Freelance",
            location: " Kuala, Malaysia",
            workTime: " 10 hours ago",
            salary: " $30k",
        },
        {
            id: 1,
            title: "Marketing Assistant",
            company: "Spotify",
            level: "Senior", 
            image1: image7,
            image2: spotify,
            typeWork: "Part Time",
            location: " California, USA",
            workTime: "8 days ago",
            salary: " $20k-30k",
        },
        {
            id: 2,
            image1: image8,
            image2: twitter,
            title: "Programmer",
            company: "Twiter",
            level: "Senior",
            typeWork: "Part Time",
            location: " tartus, syria",
            workTime: "8 days ago",
            salary: " $20k",
        },
        {
            id: 3,
            image1: image10,
            image2: yelp,
            title: "HR Manager",
            company: "Yelp",
            level: "Senior",
            typeWork: "Part Time",
            location: " lattakia, syria",
            workTime: "15 hours ago",
            salary: "$35k - 45k",
        },
        {
            id: 4,
            image1: image11,
            image2: paypal,
            title: "Sales Representative",
            company: "Paypal",
            level: "Junior",
            typeWork: "Contract",
            location: " damascus, syria",
            workTime: "20 days ago",
            salary: "$20k - 35k",
        },
        {
            id: 5,
            image1: image13,
            image2: envato,
            title: "Graphic Designer",
            company: "Envato",
            level: "Mid Level",
            typeWork: "Full Time",
            location: "Melbourne, Australia",
            workTime: "2 days ago",
            salary: " $20k",
        },
        {
            id: 6,
            image1: image11,
            image2: paypal,
            title: "Sales Representative",
            company: "Paypal",
            level: "Senior",
            typeWork: "Contract",
            location: "Melbourne, Australia",
            workTime: "20 days ago",
            salary: "$100k - 50k",
        },
        {
            id: 7,
            image1: image14,
            image2: twitter,
            title: "Programmer",
            company: "Twiter",
            level: "Senior",
            typeWork: "Full Time",
            location: " California, USA",
            workTime: "8 days ago",
            salary: " $30k",
        },
        {
            id: 8,
            title: "Marketing Assistant",
            company: "Spotify",
            level: "Senior", 
            image1: image10,
            image2: spotify,
            typeWork: "Full Time",
            location: " California, USA",
            workTime: "8 days ago",
            salary: " $2k",
        },
        {
            id: 9,
            title: "Front End Devloper",
            company: "Facebook",
            level: "Junior", 
            image1: image10,
            image2: dropbox,
            typeWork: "Full Time",
            location: " California, USA",
            workTime: "8 days ago",
            salary: " $20k",
        },
        {
            id: 10,
            image1: image16,
            image2: microsoft,
            title: "Technical Lead",
            company: "Salesforce",
            level: "Internship",
            typeWork: "Freelance",
            location: " Kuala, Malaysia",
            workTime: " 10 hours ago",
            salary: " $5k - $10k",
        },
        
    ]
export const Costumers=[
    {
        id: 0,
        title: "Ali",
        image: image16,
        jop: "Front End",
        content: "Lorem Ipsum dolor sit amet, consectetur adipsicing kengan omeg kohm tokito adipcingi elit eismuod larehai,Lorem Ipsum dolor sit amet, consectetur adipsicing kengan omeg kohm tokito adipcingi elit eismuod larehai,Lorem Ipsum dolor sit amet, consectetur adipsicing kengan omeg kohm tokito adipcingi elit eismuod larehai",
    },
    {
        id: 1,
        title: "Hasan",
        image: image17,
        jop: "Flutter Dev",
        content: "Lorem Ipsum dolor sit amet, consectetur adipsicing kengan omeg kohm tokito adipcingi elit eismuod larehai,Lorem Ipsum dolor sit amet, consectetur adipsicing kengan omeg kohm tokito adipcingi elit eismuod larehai,Lorem Ipsum dolor sit amet, consectetur adipsicing kengan omeg kohm tokito adipcingi elit eismuod larehai",
    },
    {
        id: 2,
        jop: "Flutter Dev",
        title: "Haedara",
        image: image18,
        content: "Lorem Ipsum dolor sit amet, consectetur adipsicing kengan omeg kohm tokito adipcingi elit eismuod larehai,Lorem Ipsum dolor sit amet, consectetur adipsicing kengan omeg kohm tokito adipcingi elit eismuod larehai,Lorem Ipsum dolor sit amet, consectetur adipsicing kengan omeg kohm tokito adipcingi elit eismuod larehai",
    },
    {
        id: 3,
        title: "Hamed",
        jop: "Flutter Dev",
        image: image19,
        content: "Lorem Ipsum dolor sit amet, consectetur adipsicing kengan omeg kohm tokito adipcingi elit eismuod larehai,Lorem Ipsum dolor sit amet, consectetur adipsicing kengan omeg kohm tokito adipcingi elit eismuod larehai,Lorem Ipsum dolor sit amet, consectetur adipsicing kengan omeg kohm tokito adipcingi elit eismuod larehai",
    },
]